"""Generate crates/sonictok-core/src/unicode/tables.rs from Unicode data.
Requires the third-party `regex` module (same source tiktoken relies on):
    pip install regex
Run: python tools/export_unicode.py
Verify (re-derive and diff): python tools/export_unicode.py --check
"""
import sys, regex

MAX = 0x110000


def ranges_for(pattern: str) -> list[tuple[int, int]]:
    rx = regex.compile(pattern)
    out, start = [], None
    for cp in range(MAX):
        # skip surrogates; chr() rejects them
        if 0xD800 <= cp <= 0xDFFF:
            if start is not None:
                out.append((start, cp - 1))
                start = None
            continue
        hit = bool(rx.match(chr(cp)))
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def emit() -> str:
    classes = {
        "LETTER": r"\p{L}",
        "NUMBER": r"\p{N}",
        "WHITE_SPACE": r"\s",  # regex module: \s == \p{White_Space} under UNICODE
        # o200k case-aware letter classes:
        "O200K_UPPER": r"[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}]",
        "O200K_LOWER": r"[\p{Ll}\p{Lm}\p{Lo}\p{M}]",
    }
    lines = [
        "// @generated by tools/export_unicode.py — DO NOT EDIT.",
        "// Inclusive code-point ranges, sorted ascending, non-overlapping.",
        "",
    ]
    for name, pat in classes.items():
        rs = ranges_for(pat)
        lines.append(f"pub static {name}: &[(u32, u32)] = &[")
        for a, b in rs:
            lines.append(f"    (0x{a:X}, 0x{b:X}),")
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


OUT = "crates/sonictok-core/src/unicode/tables.rs"


def main() -> int:
    text = emit()
    if "--check" in sys.argv:
        with open(OUT) as f:
            cur = f.read()
        if cur.strip() != text.strip():
            print("DRIFT: tables.rs is out of date; re-run without --check", file=sys.stderr)
            return 1
        print("ok: tables.rs matches regenerated output")
        return 0
    with open(OUT, "w") as f:
        f.write(text + "\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
